### ISSUE TITLE
[21] Build Routes from the response from TfL

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#122]
> As a user, when I search for routes I need them to be saved so I can choose and view a route in the future.

When we request route data from TfL we get a lot of data back. We need to turn this data into data models and associate them with the Trip model #61 so that people can select a route.

We should only build a route model if the response we get back from TfL is successful.

## Acceptance criteria

- [x] It creates a route #60 for each `journey` in the `journey` array returned from the TfL
- [x] It creates a step #41 on a route for each `leg` in the journey. 
- [x] If a `leg` has `steps` it should create a sub-step for each step in the `leg` in the order they appear in the list.
- [x] If a `leg` is on a bus, tube or train it should create sub steps for the bus stops or tube stops en route.
- [x] It should be tested with a long trip north to south.
- [x] It should be tested with a long trip east to west
- [x] It should be tested with a multi-modal trip e.g. one that involves walking, bus and a train
- [x] It should be tested with a short walking trip
- [ ] Calling trip.build! multiple times should destroy any routes previously sourced the for trip and rebuild the routes. If someone goes back, they should get new routes as the previous routes may be stale.

## Notes and links

- A few design patterns we could explore here, one is [the Factory pattern](https://medium.com/@dljerome/design-patterns-in-ruby-abstract-factory-82b74682e04e) the other is [the Builder pattern](https://medium.com/@dljerome/design-patterns-in-ruby-builder-6c6d172e8de8)

- Rails sort of gives us a builder for free with the Rails model interface. But we have quite a lot of variations / conditionality where we need to pull different options from the TfL data depending on the mode of transport for example or whether it is a sub-step.

- We have put together [an entity relationship diagram and a mapping diagram](https://miro.com/app/board/o9J_ldiNdfU=/) to help help us plan this out.

**Comment by mathewtrivett** [comment]
Currently blocked by #123 and #113

**Comment by mathewtrivett** [comment]
I think this is now unblocked @francosta

**Comment by francosta** [comment]
I think so @mathewtrivett. I'm moving it to 'Doing' as it's the one I'm working on now.
