### ISSUE TITLE
[13] Set up stylesheet for print

### ISSUE THREAD

**Issue by francosta** [WeAreSnook/connected-camden#131]
> As a system, I need a stylesheet to set the styles of the journey plan when it is printed.

## Acceptance Criteria

- [x] There is a stylesheet that implements the design for the printed version of the journey plan.
- [x] The stylesheet is applied to the journey plan when the user clicks the 'Print' button (#129).
- [x] We have a separate stylesheet_link across that application that loads when the "media" is "print"

**Comment by mathewtrivett** [comment]
Closing this ticket and documenting all requirements on #211
