### ISSUE TITLE
[21] Preview my selected route

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#136]
> As a user, when I have selected a route I want to see it so I can decide if this is the route I want to take or not.

This is the bulk of the product, once someone has put in their trip details we will show them the route end to end.

Top level steps = These define the main legs of the journey and change when the transport mode changes e.g. walking, bus, train

Sub-steps = These are the details steps in each leg of the route.

## Acceptance criteria

- [x] It should assign a `@trip` attribute
- [x] It should assign a `@route` attribute
- [x] It is expected to render the StepHeader markup for each top level step in the route.
- [x] With walking steps it is expected to render the markup for a RouteStep for each sub-step in a walking leg of the journey.
- [x] With non walking steps, the steps after the first sub-step should be rendered as a TransportStep
- [x] With non walking steps, the first sub-step in this leg should be rendered as a RouteStep
- [x] The components should be styled using tailwind css classes and should match the designs from the design system
- [x] It should not include the markup for buttons, images or text boxes.
- [x] It should be built using mobile first approaches

## Notes and links

- We have created [a miro board](https://miro.com/app/board/o9J_ldiNdfU=/) with the data model that the project uses.
- [Design files](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover)

- [Tailwind CSS cheat sheet](https://nerdcave.com/tailwind-cheat-sheet)
- Tailwind CSS Documentation https://tailwindcss.com/docs/utility-first

- Tailwind Intellisense https://tailwindcss.com/docs/intellisense

**Comment by endyranaudo** [comment]
## Adds  

- Generated `routes_controller` and added a `show method` to it
- Created a Trip instance in the Seed file
- In `route.rb` Added a nested `Route` in Trip so we can have `/trips/:id/routes/:id`
- Set-up Roboto as font-family for the whole project (check `tailwind.config.js`)
- Added some styling (Tailwind) to `step_header_component` and `route_step_component`

## Changes  
- Removed the size attributes in the SVG file
- Changed step.mode `public-bus` to `bus`
- Added styles to `step_header_component` `route_step_component` and `transport_step_component`
- Added some custom SASS style in `app/assets/stylesheets/application.scss` to temporary fix the issue with the circle around the step number (see below).
Please delete it if not needed.

## Removes  

n.a.

## Dependencies  

n.a.

## Blockers/Issues  
- In the file `transport_step_component.html.erb` line 3 I can't set min and max value to 50px with Tailwind.
  min and max height/width values are essential to have a perfect circle around the numbers.
  Without them some circle are 48px and others 50px. I had to add custom SASS styling.
- Some margin/border sizes in the design are not included in tailwind  (some `div` needs `margin-bottom 91px`)

## Future improvements  

- As we did for the font, we might need to edit the theme in  `tailwind.config.js` with our custom assets (colours, font-size etc).
- Need to carry on with styling the components
