### ISSUE TITLE
[5] Search for routes from TfL

### ISSUE THREAD

**Issue by HarryPotia** [WeAreSnook/connected-camden#155]
> As a system, when I have a valid Trip query I want to fetch possible routes from TfL so that users can choose their preferred route.

The Rails way focusses on keeping domain logic inside our models and not in controllers. Currently we are loading the RoutePlanner service inside the controller. But we probably want to encapsulate this functionality inside the trip model itself.

We could have a method like `Trip.fetch_routes` which takes our TfL query and sends a request to TfL.

Then in #122 we can use this `Trip.fetch_routes` method can be used to inside something like a `Trip.build_routes` method.

This way we keep our Controllers lean and keep domain logic inside our Model.

## Acceptance criteria

- [x] We should have an instance method on our Trip called `fetch_routes`
- [x] It should make a web request to the TfL API using the `to_tfl_query` method and the `RoutePlanner` Service
- [x] It should return a Hash
- [x] This might involve having a `route_planner` method on our Trip that returns a configured instance of the RoutePlanner service.

**Comment by mathewtrivett** [comment]
@francosta I've added some detail / acceptance criteria here. If there it is not clear then say and ask for some clarification. If it is clear then could you remove the needs updating label.

**Comment by francosta** [comment]
Thank you @mathewtrivett - all's clear and dI'll remove the label.
