### ISSUE TITLE
Component: Step header

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#172]
The Step header component is used for the top level step in each route.

It provides a summary of the mode of transport, instructions and duration of the step.

We are using the [ViewComponents](https://viewcomponent.org/) gem to create reusable components using Ruby.

## Acceptance criteria

- [x] It is expected to be initialized with a required `step:` attribute Step model. 
- [x] It is expected to have an `@step` attribute equal to the `step` passed in the initialize method
- [x] It is expected to render a h2 with the `@step.title`
- [x] It is expected to have no rubocop errors. Run `rubocop -A` to automatically fix any fixable errors.

## Acceptance criteria - with `walking` mode

- [x] It is expected to render a SVG walking icon
- [x] It is expected to render a span with ‘X minutes’ where X is the duration of the step
- [x] If the duration is only one minute it should say `1 minute`

## Acceptance criteria - with `public-bus` mode 

- [x] It is expected to render a SVG bus  icon
- [x] It is expected to render ‘X stops’ where X is the `step.steps.count`
- [x] It is expected to render `1 stop` where `step.steps.count` is equal to 1
- [x] It is expected to render `About Y minutes` where Y is the `step.duration`
- [x] It is expected to render `About 1 minute` where the `step.duration` is equal to 1

## Acceptance criteria - with `tube` mode

- [x] It is expected to render a SVG tube icon
- [x] It is expected to render ‘X stops’ where X is the `step.steps.count`
- [x] It is expected to render `1 stop` where `step.steps.count` is equal to 1
- [x] It is expected to render `About Y minutes` where Y is the `step.duration`
- [x] It is expected to render `About 1 minute` where the `step.duration` is equal to 1

## Acceptance criteria with `overground` mode

- [x] It is expected to render a SVG overground icon
- [x] It is expected to render ‘X stops’ where X is the `step.steps.count`
- [x] It is expected to render `1 stop` where `step.steps.count` is equal to 1
- [x] It is expected to render `About Y minutes` where Y is the `step.duration`
- [x] It is expected to render `About 1 minute` where the `step.duration` is equal to 1

## Acceptance criteria - with `train` mode

- [x] It is expected to render a SVG train icon
- [x] It is expected to render `About Y minutes` where Y is the `step.duration`
- [x] It is expected to render ‘X stops’ where X is the `step.steps.count`
- [x] It is expected to render `1 stop` where `step.steps.count` is equal to 1
- [x] It is expected to render `About 1 minute` where the `step.duration` is equal to 1

## Notes and links

- Here is an [example of a Step Header](https://www.figma.com/file/VLt83oAghwH6xwRu5k6kEv/CamCC---Design-Library?node-id=147%3A0) in the design library.

- You can [see this more fully in the prototype](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=77%3A2269)

- Valid modes provided by TfL are `public-bus`, `overground`, `train`, `tube`, `coach`, `dlr`, `cablecar` , `tram`, `river`, `walking`, `cycle`

- Rails provides the pluralize helper to pluralize text https://apidock.com/rails/ActionView/Helpers/TextHelper/pluralize

**Comment by endyranaudo** [comment]
I need to figure out how to conditionally render an SVG.
