### ISSUE TITLE
Style the RouteStepComponent

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#244]
The Route step component is a general component used to represent a step in the route. It's subcomponents change depending on the context in which it is used.

## Acceptance criteria

- [x] Styling rules should use the [Block-Element-Modifier (BEM) approach](http://getbem.com/introduction/) for CSS class names.
- [x] Use [the @apply function from tailwindcss](https://tailwindcss.com/docs/extracting-components#extracting-component-classes-with-apply) to apply tailwind utility classes as much as possible.
- [x] Screen styles should be defined in the `application.scss` file
- [x] Print styles should be defined in the `print.scss` file

## Notes and links

- You do not need to style the EditStepFormComponent in this ticket.
- [An example of the print styles for this component](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=493%3A50).
- [An example of the screen styles when not editable](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=569%3A2919)
- [An example of the screen styles when editable](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=369%3A3332)

**Comment by endyranaudo** [comment]
Looking at the design, I'm not sure I need to add at this stage the button "Add notes here" and the "success" message that we render in case we edit the title of the step ("Your notes have been changed successfully!"). 
I assume that both need to be a component, so they might need a new ticket

**Comment by mathewtrivett** [comment]
@endyranaudo no, there's no need to style those in this ticket. The EditStepForm component already exists which is the "Add notes here" but the notice component doesn't.

I've also finished off the styling for screens on #249
