### ISSUE TITLE
Add box-shadow on focus to inputs and buttons

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#258]
If people are using their keyboard to navigate the application it can be quite confusing to know where your cursor is. We want to highlight the selected field.

As we have rounded corners we should use a solid box-shadow rather than the outline property. This way the focus state will follow the rounded corners.

## Acceptance criteria

- [x] Add `box-shadow: 0 0 0 5px gold` to buttons when focussed
- [x] Add `box-shadow: 0 0 0 5px gold` to links styled as buttons when focussed
- [x] Add `box-shadow: 0 0 0 5px gold` to the typeahead inputs when focussed

## Notes and links

- This is already implemented on the checkboxes on #257 when merged in for reference.

**Comment by endyranaudo** [comment]
I'm going to create a pull req for this ticket. I've run some test and it seems that everything works.
There is some code duplication:
- I've added style on the application level so it can be available in the whole app
- Some components have ``focus`` utility classes from Tailwind. We should tidy up the code once (and if) my solution gets approved.
