### ISSUE TITLE
Style the Journey Header Component

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#265]
The journey header is used to give an overview of the overall journey.

## Acceptance criteria

- [x] It should have a title with the text `From x to y` where x is the `@route.trip.start_point.address` and y is the `@route.trip.end_point.address`
- [x] It should include text `x minutes` where x is the the `duration` property of the Route.
- [x] It should be visible on the `routes/edit.html.erb` view
- [x] It should be visible on the `routes/show.html.erb` view
- [x] It should be visible on the printed route view
- [x] It should be styled as per the designs below

## Notes and links

- [Large screens](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=569%3A2919)
- [Small screens](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=569%3A3129)
- [Print](https://www.figma.com/file/VEbdqewes6kebDJcy8aVRX/CamCC---Handover?node-id=91%3A1685)

**Comment by endyranaudo** [comment]
CircleCI test does not pass. I ran `rubocop -A` and `rspec` with no issues/fail.
I'll need some help with that, I can't see the logs in CircleCi (do I need to create an account?)
