### ISSUE TITLE
Background reading

### ISSUE THREAD

**Issue by HarryPotia** [WeAreSnook/connected-camden#27]
> As a design team we need to do some background reading into the product space we are designing for so we can build on current best practices.

## Acceptance criteria

- [ ] We have a shared list of background reading links

## Background reading list:

- [Helping people get from A-to-B](https://docs.google.com/presentation/d/1amatd1Vn621Vp37vSZlXnULdHPvbiMTpBHH-jlDSXfw/edit#slide=id.g5ef40191f1_0_1341)

- [Research during Covid](https://drive.google.com/drive/folders/1Yc_87q0zpuWnvvW4xKFvwUI37KchxafZ)

**Comment by mathewtrivett** [comment]
@vandagomes can you drop links in here / document the background reading you did? So create a sort of reading list for someone new to the project

**Comment by vandagomes** [comment]
Will do @mathewtrivett maybe on monday afternoon
