### ISSUE TITLE
Decide on a mapping provider

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#36]
> As a team
> we need a mapping provider
> so that we can show users maps, routes and points of interest

---

## Description

We need to decide on a mapping provider to use. Most mapping providers don't allow mixing and matching with their competitors in their terms of service. So for example we couldn't use place search from Google but then Mapbox maps. To help us better evaluate which mapping provider to use we need some criteria to evaluate them against.

## Candidates

- [Google Maps and Places](https://developers.google.com/places/web-service/overview)
- [Mapbox](https://docs.mapbox.com/api/search/)
- [Algolia places](https://community.algolia.com/places/)

## Acceptance criteria

- [ ] We can customise the design of the map
- [ ] Supports reverse geocoding
- [ ] Supports autocomplete for reverse geocoding
- [ ] Has a Ruby client or an open source Ruby client is available
- [ ] Allows us to draw lines on a basemap
- [ ] Allows us to draw points and labels on a base map
- [ ] Allows us to render our own mapping layers / extra data
- [ ] Allows us to draw polygons on a basemap
- [ ] Is accessible or has accessibility features

**Comment by tosbourn** [comment]
I don't believe our current designs or feature set necessitate a mapping provider for drawing maps, so I would be tempted to reprioritise that in favour of the features we 100% need, which is reverse geocoding.

So long as other providers can do reverse geocoding, swapping in the future won't be an issue.

**Comment by vandagomes** [comment]
I agree with Toby. 

From discovery, we learnt that **people don't understand maps**. We know that people that are helping feel the need of using to techniques like drawing their own maps. I also believe that a map is not accessible.

**Comment by mathewtrivett** [comment]
I think this is a dead issue now based on the discussion above.
