### ISSUE TITLE
[5] Homepage

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#37]
> As a new user
> I want to understand making a journey
> So that I can prepare and situate myself

---

## Description

We need people to be able to know what they are getting themselves into by using our form, we also need a place to display current government guidance.

## Acceptance criteria

- [x] Visiting the root path `/` will take you to the homepage
- [x] Using root_path in rails will take you to the homepage
- [x] Visiting the homepage will have a:
- [x] title #38 
- [x] one or more paragraphs of explanatory text
- [x] a list of current government guidance
- [x] a link to take you to plan your trip #39

**Comment by francosta** [comment]
I have discussed this issue with @tosbourn and clarified the way to build the homepage.
As we will have hardcoded text in the homepage, aside from the components, we don't need a model or `factory_bot_rails`.
