### ISSUE TITLE
[5] Form: Ending Point

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#43]
Our multi step form requires several unique sections, each section has its own design and data challenges.

This part of the form captures the ending point, it is used to capture the ending point of our journey.

This ticket is not interested in performing the lookups eventually required to find the exact starting point of a journey

## Acceptance Criteria

- [x] A single text input box with the label "Where's your destination?"
- [x] A back link that will take you back to the starting point screen #42 
- [x] Entering text into the fiend will present you with multiple potential options (these can be hard coded as part of this ticket)

**Comment by francosta** [comment]
@tosbourn would the 'Back' link take the user to the very start of the form or to the previous one? (i.e., the previous on is the #105 (journey starting preview) and the start one is #42 (form starting point).
