### ISSUE TITLE
Set up ViewComponent

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#47]
To mimic other Rails projects that use components, we want to use the [ViewComponent](https://github.com/github/view_component) gem to generate some of the frontend components.

As well as installing the gem as per its README, we should also add the RSpec helpers (also mentioned in the README).

## Acceptance Criteria

- [x] Install View Component gem
- [x] Set up relevant RSpec helpers
- [x] Write a brief technical decision record on using ViewComponents

**Comment by mathewtrivett** [comment]
@francosta sorry to do this, especially when you've just pushed a Pull Request. But could you write a short technical decision record on using ViewComponent, as it may be new to developers who havn't used it before.
