### ISSUE TITLE
Form: How would you like to travel

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#53]
Our multi step form requires several unique sections, each section has its own design and data challenges.

This part of the form captures how someone would like to travel, allowing them to select multiple options.

## Options

The options are:

- Public transport
- Walking
- Cycling
- Taxi, Uber, etc

## Acceptance Criteria

- [ ] A list of options with the label "How would you like to travel?"
- [ ] A back link that will take you back to the journey end selection screen
- [ ] You can select multiple checkboxes, but must select at least one to progress
- [ ] Clicking Next brings you to the "what mode of transport?" section if "public transport" was ticked
- [ ] Clicking Next brings you to the "walking preferences" section if "public transport" was not ticked

**Comment by tosbourn** [comment]
@vandagomes thinking more about the Taxi option - what do you think we'd be suggesting to people who click that?

Presumably the next steps would be to use Uber and set a destination.

**Comment by vandagomes** [comment]
@tosbourn this is def something we still need to figure it out... From discovery we know that people prefer to travel by taxi. But when we say taxi are we including ubers? My thinking was that how are these influencing the journey and the planning? A taxi might have "stops" or local pick up places maybe while uber don't.

**Comment by mathewtrivett** [comment]
Also worth considering that I believe people who have adult social care support can access discounts, possibly free travel with Taxi companies. TfL doesn't provide us with any taxi data and so we will likely need to integrate with some other service, and as we are discussing there is likely to be a pretty different flow / user experience for this.

I wonder whether travel by taxi is a feature all of its own?

**Comment by mathewtrivett** [comment]
Actually what am I talking about! TfL doooo have Taxi data https://api.tfl.gov.uk/swagger/ui/index.html?url=/swagger/docs/v1#!/Cabwise/Cabwise_Get

**Comment by LiamHinshelwood** [comment]
Yeah, this is a great question. I wonder if the user need(s) is/are slightly different here, especially if they have already chosen to take a taxi. If we stick to our planning remit, from a users perspective, what needs to be planned about a taxi journey and how can the product support this?

_As a user with accessibility needs, I need my taxi journey to ..., so that I can travel independently, safely and with confidence._

It may be that this doesn't fall entirely within the scope of the route planner we are building out so far. And as Mat pointed out, we may need to build in additional functionality/contact details to specific taxi providers.

We may be able to pick this up with our teat pilots!

**Comment by mathewtrivett** [comment]
@vandagomes @francosta could we clarify what the difference is between this and #54 ?

In terms of TfL, there is only really a travel mode option. To define a travel mode. I just want to avoid us doing work which is duplicated?

**Comment by mathewtrivett** [comment]
These are the options TfL gives us to query routes for:

- public-bus
- overground
- train
- tube
- coach
- dlr
- cablecar
- tram
- river
- walking
- cycle

People can select more than one, or we could just provide a sublist

**Comment by vandagomes** [comment]
@mathewtrivett we removed this from the designs as it was adding an unnecessary step to the journey. We only have #54 atm. I think on that step we still need to ask/test: what transports from the list you just shared makes sense to have in here?

**Comment by francosta** [comment]
Yes, this I don't think is a requirement anymore - right, @tosbourn?
It was an intermediate step between actually choosing the modes of transport (bus, tube, etc.) and a more generic one (public transport, walking, cycling).

**Comment by mathewtrivett** [comment]
Ok create, shall we close this ticket and use #54 instead?

**Comment by vandagomes** [comment]
yes!
