### ISSUE TITLE
[21] Form: Accessibility requirements

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#57]
Our multi step form requires several unique sections, each section has its own design and data challenges.

This part of the form captures if someone has accessibility requirements

## Options

The options are:

- No accessibility requirements
- Use escalators, not stairs
- Use stairs, not escalators
- Full step-free access
- Step-free to platform only

## Acceptance Criteria

- [x] A list of options with the label "Do you have any accessibility requirements?"
- [x] A back link that will take you back to the "walking preferences" selection screen
- [ ] You can select a single radio button
- [x] Clicking Next brings you to the "travel time" section having saved your preferences
- [x] Clicking Skip this step brings you to the "travel time" section having not saved your preferences

**Comment by tosbourn** [comment]
@vandagomes just thinking about these options, I wonder if "No accessibility requirements" can be removed because you can just skip/next without selecting anything.

I guess with radio buttons this would act almost like a "clear" for if someone selected something by mistake and didn't think to "skip"

**Comment by vandagomes** [comment]
I understand where you are coming from @tosbourn Essentially selecting that option or skipping will lead the user to the same result/route options. However I think for the user its more straightforward having that option when its a clear call to action than skipping the step. Skipping the step would mean something like 'I don't mind' or 'I don't relate with this' in my opinion

**Comment by mathewtrivett** [comment]
@vandagomes on this, with the TfL API we can query for multiple accessibility requirements. For example only show me routes without escalators and with step free access. This suggests these would be better as checkboxes allowing people to select multiple options.


@tosbourn having played around here a bit, I think the model could benefit from a little change to make it easier to integrate. See pseudo model below:

```ruby
class AccessibilityPreferences
      @label label
      @value value
      @order order
```

This would allow us to store the TfL value in the value attribute and human readable label in the label attribute. We could then use this pattern across other Objects that represent options passed to TfL.

**Comment by mathewtrivett** [comment]
@tosbourn I may need a bit of support here as I feel like I might have hit a bit of a blocker. The challenge is with saving selected preferences. On the starting point form we create a Trip ActiveRecord object from data persisted in the session. 

To continue down this line of thought I have created an AccessibilityPreference model and a many to many through relationship with Trip. So now a `Trip.has_many :accessibility_preferences, through: :trip_accessibility` and `AccessibilityPreference.has_many :trips, through: :trip_accessibility`.

In order for our form to work, we need to display all of the available accessibility options and check the ones that belong to this trip. However, our CheckBox component is quite primitive it is currently expecting a Hash with the shape:

```ruby
{
    label: 'Label',
    value: 'camelCasedValue'
    selected: true
}
```

## Options

### A query that returns the data in the format above. (Preferred option)

This would allow us to query the data in the controller and pass it directly to the CheckboxComponent without a need to change the CheckboxComponent. I'm not clear on whether Rails allows you to do something like this, for example create a new attribute "selected" if the trip is in the AccessibilityPreference.trips?

This feels the most Rails way of keeping models fat.

### A method that returns a boolean if the AccessibilityPreference is selected on the trip.

This could be used in the view to check or uncheck the box. 

```ruby
class AccessibilityPreference

def is_selected(trip)
   self.trips.exists? trip
end
```


Or some other way?

**Comment by tosbourn** [comment]
@mathewtrivett congratulations, you've just uncovered one of the most inconsistent solutions I've spotted on forms that use components. 🎉 

Seriously though, I've seen about 5 different ways of doing this, each with their own unique tradeoffs.

I like keeping components dumb, in that we pass in some stuff, and they react to that stuff. They shouldn't need to care about the objects in our system, just their values.

Given our relatively lightweight needs for this, I'm tempted to suggest a very light bit of decoration on the `AccessibilityPreference` model.

Adding to what you've written, something like:

```
def self.options_for(trip)
  all.map do |option|
   {
    label: option.name,
    value: option.name.camelcase
    selected: option.is_selected(trip)
   }
  end
end
```

This (written off the top of my head, probably broken) code would return an array of hashes, allowing us to pass in `AccessibilityPreferences.options_for(trip)` to the component.

**Comment by mathewtrivett** [comment]
Nice....I like this solution. I think I got stuck trying to figure out how to do it with SQL and the query interface but this makes so much more sense. I can write some tests for that and get something working.

**Comment by vandagomes** [comment]
@mathewtrivett not sure how could these work with checkboxes.

At the moment, the options are: 
- No accessibility requirements
- Use escalators, not stairs
- Use stairs, not escalators
- Full step-free access
- Step-free to platform only

Maybe we could try to separate them but we would need to think about a new logic:
- Full step-free access
- Without escalators
- Without stairs

Something like this... Not sure! Also we need to be clear in the language that these only applies to stations.
