### ISSUE TITLE
[21] Model: Route

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#60]
A Route is the end-to-end journey. It is made up of an ordered series of `Steps` and contains an optional descriptor (e.g "Fewest changes")

In order to properly display routes, and their steps, we should store their information in a model.

When we pull data down from TFL, we will be storing it in `Steps` and `Routes`

A `Route` will have:

- duration (integer)
- start_date_time (timestamp)
- end_date_time (timestamp)

A route has the following relationships

- A has_many `Steps` #41 

## Acceptance Criteria

- [x] Be able to create a route by calling `Trip.routes << Route.last`
- [x] Be able to create a `Route` by calling `Route.create!(duration: 20, start_date_time: '', end_date_time: '')`
- [x] Be able to attach a `Step` to a `Route` - `my_route.steps << Step.last`

**Comment by tosbourn** [comment]
@francosta @mathewtrivett 

Given the work done so far with talking to TFL, do you feel this pattern works?

Route -> Step -> Step

So one call might bring back two `Routes`

These routes are made up of steps, and lots of sub steps (which are just steps whose parent is a step, not a route)

A step would be destroyed by it's route being destroyed.

**Comment by mathewtrivett** [comment]
I wonder if we model the Route as closely as possible to the TfL API then we can better version it as things change, this could makes building ActiveRecord instances easier?

We likely don't need all the data returned from TfL but you could get a good window into the Shape of the TfL data model by looking at the GraphQL types I put together for the tfl-graphql playground.

This is the Itinerary result type that is returned from a Journey search. You should be able to jump to all of the other models by clicking on the class names 
https://github.com/mathewtrivett/tfl-graphql/blob/main/app/graphql/types/tfl/entities/journey_planner/itinerary_result_type.rb

I could have a go at putting together a data model diagram if that would be helpful?

**Comment by francosta** [comment]
I think what @tosbourn said would work.
I agree with @mathewtrivett in that it would make life easier if we could model `Route` as much as possible with the TfL API response. But in that sense, `Route` would map to `Journey` in the API and each `step` would be a `leg`. That way we would get the desired behaviour of a single call bringing back multiple `Route`s.

**Comment by mathewtrivett** [comment]
I agree with the principle of YAGNI `Ya Ain't Going to Need it` and `Minimum viable data model (not a thing)`. I really don't think we should replicate the whole TfL data model in our app, but it might be good to have a bit more of an overview of the data model we need now and might need in the future.

**Comment by francosta** [comment]
Yes definitely - I didn't mean making `Route` the same as the TfL response. Just meant that we should model those bits we need to it. Definitely not the whole thing 👍

**Comment by mathewtrivett** [comment]
I think we would benefit here from a bit of research and planning time, see #123
