### ISSUE TITLE
[21] Model: Trip

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#61]
A Trip is all of the preferences that a user has entered in order to help us select appropriate routes for them.

In order to properly allow a user to edit or create a `Trip` we should store it in a model

A `Trip` has the following relationships

- has_many `Routes` #60 
- has_one `WalkingSpeed` #64 
- has_one `StartPoint` #116 
- has_one `EndPoint` #163
- has_one `WalkingTime`
- has_many `TransportModes`, through: TripTransportMode #62 
- has_many `AccessibilityRequirement`, through: `TripAccessibility` #66 
- has_many `TravelTimes`
- has_many `TravelDays`

## Acceptance Criteria

- [x] Be able to create a `Trip` by calling `Trip.create!` with all required attributes
- [x] Be able to attach a `Route` to a `Trip` - `my_trip.routes << Routes.last`
- [x] Be able to add a `StartPoint` to a `Trip` by calling `Trip.start_point = StartPoint()`
- [x] Be able to add a `EndPoint` to a `Trip` by calling `Trip.send_point = EndPoint()`
- [x] It is expected to accept_nested_attributes_for `:start_point`
- [x] it is expected to accept_nested_attributes_for `:end_point`

**Comment by mathewtrivett** [comment]
I'm editing this Trip model based on the discussion on #53 . We had a duplicate form step and set of models including #63. This has been reduced now to just #62 . The edits above reflect this.
