### ISSUE TITLE
Model: PublicTravelOption

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#63]
A PublicTravelOption is one of the preferences used in a `Trip`.

In order to properly allow a user to edit or create a `Trip` we should store these preferences in a model, and allow an individual `Trip` to have access to them.

A `PublicTravelOption ` will have:

- name (string) required
- position (integer) required

Position is used as an admin function if we wanted to change the order options were displayed

A `PublicTravelOption ` has the following relationships

- has_many `Routes`

To facilitate this we may need join tables to link two has_many relationships together.

## Acceptance Criteria

- [ ] Be able to create a `PublicTravelOption ` by calling `PublicTravelOption.create!(name: 'Taxi', position: 1)`

**Comment by mathewtrivett** [comment]
I am going to close this ticket as it is surplus to requirements. Based on the discussion on #53. 

Instead I'm going to rename #62 to TransportMode.
