### ISSUE TITLE
[8] Model: AccessibilityRequirement

### ISSUE THREAD

**Issue by tosbourn** [WeAreSnook/connected-camden#66]
A AccessibilityRequirement is one of the preferences used in a `Trip`.

In order to properly allow a user to edit or create a `Trip` we should store these preferences in a model, and allow an individual `Trip` to have access to them.

A `AccessibilityRequirement` will have:

- name (string) required
- position (integer) required

Position is used as an admin function if we wanted to change the order options were displayed

A `AccessibilityRequirement` has the following relationships

- has_many `Routes`

To facilitate this we may need join tables to link two has_many relationships together.

## Acceptance Criteria

- [x] Be able to create a `AccessibilityRequirement` by calling `AccessibilityRequirement.create!(name: 'Taxi', position: 1)`

**Comment by mathewtrivett** [comment]
Could I just clarify here that a Trip can only ever have one Accessibility Requirement? The Accessibility Requirement form uses radio buttons which only allow for one item to be selected. However the TfL API allows for multiple accessibility preferences to be set.

See
https://api.tfl.gov.uk/swagger/ui/index.html?url=/swagger/docs/v1#!/Journey/Journey_JourneyResults

Should we refactor both this and #57 to allow for the selection of multiple options?

On this basis we would like want a many to many relationship with Accessibility Requirements so something like:

```ruby
class Trip
    has_many :accessibility_preferences, through: :trip_accessibility_preference
end
```

```ruby
class AccessibilityPreference
    has_many :trips, through: :trip_accessibility_preference
    validates :order, presence: true
end
```

```ruby
class TripAccessibilityPreference
    belongs_to :trip
    belongs_to :accessibility_preference
end
```

This would allow for Admins to create Accessibility Preferences and Trips associate with them.

**Comment by tosbourn** [comment]
@mathewtrivett great question.

I made this ticket as per the designs, @mathewtrivett can you check with @vandagomes what is best here.

If we allow multiple then your proposed solution looks a++
