### ISSUE TITLE
Evolve testing learnings - Sprint 1

### ISSUE THREAD

**Issue by vandagomes** [WeAreSnook/connected-camden#77]
## Acceptance criteria
- [ ] Testing Analysis 
- [ ] Clarify learnings and Insights
- [ ] Update prototype

**Comment by HarryPotia** [comment]
@vandagomes i've just updated the title of the ticket and added Sprint 1, as it looks like an ongoing task with repeatable AC's. Let me know if otherwise.

**Comment by mathewtrivett** [comment]
@vandagomes @HarryPotia can we close this ticket?

**Comment by vandagomes** [comment]
Yes we can
