### ISSUE TITLE
Spike - Journey Planning

### ISSUE THREAD

**Issue by francosta** [WeAreSnook/connected-camden#9]
## Background

We are going to use the TfL API to support the journey planning core feature. There needs to be research done on how we can best use the API as well as its limitations and requirements. The TfL API is likely to be one of the pieces of technology in which the product is most reliant. It is very important we are sure of the ways we can/cannot use it.

Journey planning also presents some challenges in terms of building the user interface, namely in relation to using a map (which still is to be decided in the design process).

## Goals

- Understand which API(s) in the product to use, in order to support the feature;
- Find what data we require in order to request data from the API;
- Understand what data we can get from the required APIs;
- List the technical requirements to use the API;
- Learn the accessibility options the API provides;
- Understand the limitations of the API (e.g., number of requests allowed, potential costs, etc.);
- Understand how we can plot a journey on map (?)
- List mapping APIs and technologies available, including any limitations;
- Select the best form technology to use.

## Approach

In order to research the TfL API, I will register for an account and go through the [documentation](https://api-portal.tfl.gov.uk/product#product=2357355709892).
I will produce a simple document to answer each of the goals and create a simple application with some sample requests.

**Comment by tosbourn** [comment]
Now that we're aligned on using Ruby, I started doing some research to see if there were any decent gems that could help.

The first project I knew of was from our very own @mathewtrivett! https://github.com/mathewtrivett/tfl-graphql - it doesn't fit our immediate needs, but can definitely be a great source of inspiration.

The most aligned gem seemed like https://github.com/LukeHackett/tfl_api_client, however it hasn't been updated in three years and we know that the TfL API has had some fairly recent changes.

Whilst it might not be worth using (we can always test it once we know the types of end points we want to hit) I think it will be useful inspiration for making our own calls from the application.

Given the tight timeframe I would not suggest making our own gem or writing a general purpose library for interacting with the API.

**Comment by mathewtrivett** [comment]
The Tfl-graphql project I'm building actually uses Luke Hackett's TFL API Client for calling the TFL API.

It's seems to have good test coverage and seems to work great when I've used.

I would agree on not building an API client from scratch for the TFL API. TFL's API is very extensive and I would say that its an Epic level ticket to build a client around it. 

A few notes from my exploration with `tfl_api_client`.

- It uses [VCR](https://github.com/vcr/vcr) and [webmock](https://github.com/bblimke/webmock) to stubbing out HTTP requests. In tests we are going to need to somehow stub or mock HTTP requests to the TFL API, otherwise our test suite has a dependency on a network connection.

If you want any support with VCR, I learned a bit about it when playing with it for the project I was working on.

**Comment by francosta** [comment]
## Select origin and destination

We'll need to use Google Maps for place search. TfL's place APi is quite poor on results from a few simple searches.

In order to search for both origin and destination we should use the [Google Places API](https://developers.google.com/places/web-service/overview).

We can use [Place Search](https://developers.google.com/places/web-service/search#TextSearchRequests) in order to get information on place search by text. This will get us matches for addresses (complete and incomplete and including post code only) as well as places like business names.

Request to `https://maps.googleapis.com/maps/api/place/textsearch/output?parameters`, where `output` is `json`.
We can use `location` and `radius` optional parameters in order to specify Camden's location with a radius from the coordinates of the borough.

We will need a Google Cloud Application as well as an api key.

Sample requests/responses:

Request:
`https://maps.googleapis.com/maps/api/place/textsearch/json?query=E28AG&key={{key}}`

Response:
`
{
    "html_attributions": [],
    "results": [
        {
            "formatted_address": "Kingsland Rd, Hackney, London E2 8AG, UK",
            "geometry": {
                "location": {
                    "lat": 51.5300549,
                    "lng": -0.0778623
                },
                "viewport": {
                    "northeast": {
                        "lat": 51.53140897989272,
                        "lng": -0.07631757010727776
                    },
                    "southwest": {
                        "lat": 51.52870932010728,
                        "lng": -0.0790172298927222
                    }
                }
            },
            "icon": "https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/geocode-71.png",
            "name": "E2 8AG",
            "place_id": "ChIJ0x6q7bscdkgRCHUwT_MxQTo",
            "reference": "ChIJ0x6q7bscdkgRCHUwT_MxQTo",
            "types": [
                "postal_code"
            ]
        }
    ],
    "status": "OK"
}
`
