### ISSUE TITLE
Setup tailwind css

### ISSUE THREAD

**Issue by mathewtrivett** [WeAreSnook/connected-camden#95]
We have decided to use TailwindCSS as our CSS framework for this project. Tailwind provides us with a utility class first approach to CSS but also the ability to build our own component styles from tailwind classes.

Read more on how to get tailwind set up on the [Tailwind docs](https://tailwindcss.com/docs/installation)

## Acceptance criteria

- [x] Tailwind and autoprefixer is installed as dependencies in our package.json file
- [x] We have a tailwind.config.js file in the root of the project generated by tailwind. We will use these to set our theme.
- [x] We have set PurgeCSS set up to [tree shake](https://webpack.js.org/guides/tree-shaking/) any unused classes and keep our css file small.

## Notes and links

Tailwind can be a bit of a pain to set up. I've written a short tutorial below that should help you complete this ticket. If you get stuck, the Tailwind documentation is pretty good and there are some blogs out there too.

### 1. Install tailwindcss and autoprefixer

Run `yarn add tailwindcss autoprefixer`

> What is autoprefixer? Not all browsers support the full range of css attributes we might want to use. For example some older browsers don't support flexbox. Autoprefixer adds prefixes to our css so our styles will work across all browsers.

### 2. Generate the tailwindcss config

In the project root run `npx tailwindcss init`

> This will create a file that we can use to configure tailwind for example defining globally used theme variables like colours and fonts.

### 3. Edit the `postcss.config.js` file

We need to require tailwind and autoprefixer in our `postcss.config.js` file. Add tailwind and autoprefixer to the plugins array.

```js
module.exports = {
  plugins: [
    require('tailwindcss'),
    require('autoprefixer'),
    require('postcss-import'),
    ...
}
```

### 4. Rename application.css to application.scss

We are going to rename `app/assets/stylesheets/application.css` to `app/assets/stylesheets/application.scss` so we can use SASS if we want to.

### 5. Import tailwind into application.scss

```scss
 *= require_self
 */

@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```

### 6. Import our stylesheet into `app/javascript/packs/application.js`

This means that Webpacker will compile our styles for us.

```js
...
require('channels');

require('../../assets/stylesheets/application.scss');
```

### 7. Add Purgecss as a dependency

Run `yarn add @fullhuman/postcss-purgecss`

### 8. Set up postcss to only purge our CSS in Production

PurgeCSS involves parsing our files and looking for patterns that look like CSS classes. This can sometimes cause performance issues in development. We only really need purgecss to run in production.

In our `postcss.config.js` file add the following as the last plugin in the array:

```js
...,
    process.env.RAILS_ENV === 'production'
      ? require('@fullhuman/postcss-purgecss')({
          content: [
            './app/**/*.html.erb',
            './app/helpers/**/*.rb',
            './app/javascript/**/*.js',
            './app/javascript/**/*.jsx',
          ],
          defaultExtractor: (content) =>
            content.match(/[A-Za-z0-9-_:/]+/g) || [],
        })
      : null,
  ],
```

First we check if we are in `production` and if so, require purgecss with the passed configuration. Essentially it is going to look for any files that end with `.html.erb`, helpers, JavaScript and JSX. If we are not in production it will return null and not load postcss.

The closing `]` here closes the plugins array.

To double check and be sure, we can also update the purge array in our `tailwind.config.js` file with:

```js
...,
purge: [
   './app/**/*.html.erb',
   './app/helpers/**/*.rb',
   './app/javascript/**/*.js',
   './app/javascript/**/*.jsx'
],
theme: {
   extend: {},
},
...
```

### 9. Take it for a test drive

In a HTML file you should now be able to add tailwind classes have them compile and style our code.

**Comment by francosta** [comment]
@mathewtrivett thank you for the very detailed ticket.
